import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

// Define all redirects here
const redirects: Record<string, string> = {
  '/doctors': '/fertility-experts',
  '/doctors/:slug': '/fertility-experts/:slug',
  '/infertility': '/treatments/infertility-treatment-in-bangalore',
  '/ivf/yoga': '/yoga',
  '/about': '/about/overview',
  '/resources/treatments': '/treatments',
  '/resources/treatments/:slug': '/treatments/:slug',
  '/features/Holistic%20Approach': '/features/holistic-approach',
  '/features/Affordable%20Treatments': '/features/affordable-treatments',
  '/features/Financing%20Options': '/features/financing-options',
  '/features/Success%20Rates%20of%20IVF': '/features/success-rates-of-ivf',
  '/features/Treatment%20Protocols': '/features/treatment-protocols',
  '/features/World%20Class%20Fertility%20Care': '/features/world-class-fertility-care',
  '/treatments/intracytoplasmic-*****-injection-icsi': '/treatments/icsi-treatment-in-bangalore',
  '/treatments/intra-uterine-insemination-iui': '/treatments/iui-treatment-in-bangalore',
  '/index': '/',
  '/treatments/infertility': '/treatments/infertility-treatment-in-bangalore',
  '/treatments/in-vitro-fertilization-ivf': '/treatments/ivf-treatment-in-bangalore',
  '/blogs/page/0': '/blogs/page/1',
  '/treatments/laparoscopy': '/treatments/laparoscopy-treatment-in-bangalore',
  '/treatments/hysteroscopy': '/treatments/hysteroscopy-treatment-in-bangalore',
  '/features/paripoorna-2024.tsx': '/features/paripoorna',
  '/features/paripoorna-2024': '/features/paripoorna',
  '/resources/diagnosi': '/resources/diagnosis',
  '/features/Best%20in%20Class%20Facilities': '/facilities',
  '/resources/diagno': '/resources/diagnosis',
  '/contact/IVF%20from%20Home': '/blogs/how-does-ivf-from-home-work',
  '/contact/Best%20in%20Class%20Facilities': '/features/best-in-class-facilities',
  '/features/IVF%20from%20Home': '/blogs/how-does-ivf-from-home-work',
  '/contact/Affordable%20Treatments': '/features/affordable-treatments',
  '/contact/Success%20Rates%20of%20IVF': '/features/success-rates-of-ivf',
  '/contact/Holistic%20Approach': '/features/holistic-approach',
  '/contact/World%20Class%20Fertility%20Care': '/features/world-class-fertility-care',
  '/contact/Financing%20Options': '/features/financing-options',
  '/contact/Treatment%20Protocols': '/features/treatment-protocols',
  '/blogs/[slug]': '/blogs',
  '/fertility-experts/[slug]': '/fertility-experts',
  '/fertility-experts/undefined': '/fertility-experts',
  '/mothers-day': '/',
  '/contact/enquiry 1': '/gg-care',
  '/about-overview': '/about/overview',
  '/best-fertility-hospital-in-bangalore': '/treatments/ivf-treatment-in-bangalore',
  '/best-ivf-center-in-bangalore': '/treatments/ivf-treatment-in-bangalore',
  '/best-ivf-fertility-hospital-in-india': '/',
  '/blog': '/blogs/page/1',
  '/blogs': '/blogs/page/1',
  '/blogs/the-psychology-of-egg-donation-insights-from-donors-and-recipients':
    '/treatments/ivf-treatment-egg-freezing',
  '/dr-asha-s-vijay-profile': '/fertility-experts/dr-asha-s-vijay',
  '/fertility-tests-for-men': '/blogs/fertility-tests-for-men-2',
  '/fertility-tests-for-men-2': '/blogs/fertility-tests-for-men-2',
  '/frozen-embryo-transfer': '/treatments/frozen-embryo-transfer',
  '/heres-how-you-can-maximize-your-ivf-success-rate':
    '/blogs/how-to-make-ivf-successful-the-first-time',
  '/home': '/',
  '/infertility-clinic-electronic-city-bangalore': '/locations/electronic-city',
  '/ivf-treatment-in-india': '/',
  '/our-fertility-team': '/fertility-experts',
  '/category/blog': '/blogs/page/1',
  '/contact/[slug]': '/gg-care',
  '/contact/Affordable Treatments': '/features/affordable-treatments',
  '/contact/Best in Class Facilities': '/features/best-in-class-facilities',
  '/contact/Financing Options': '/features/financing-options',
  '/contact/Holistic Approach': '/features/holistic-approach',
  '/contact/IVF from Home': '/features/ivf-from-home',
  '/contact/Treatment Protocols': '/features/treatment-protocols',
  '/contact4.html': '/gg-care',
  '/contact6.html': '/gg-care',
  '/contact8.html': '/gg-care',
  '/contact9.html': '/gg-care',
  '/contact-itw.html': '/gg-care',
  '/contact-nfd.html': '/gg-care',
  '/diabetes-and-infertility': '/blogs/infertility-and-diabetes',
  '/diabetes-and-infertility-2': '/blogs/infertility-and-diabetes',
  '/diet-in-infertility': '/blogs/diet-in-infertility',
  '/difference-between-icsi-ivf': '/blogs/difference-between-icsi-and-ivf',
  '/dr-asha-s-vij': '/fertility-experts/dr-asha-s-vijay',
  '/dr-asha-s-vijay-next-iui-garbhagudi-ivf-centre-tv9-kannada':
    '/fertility-experts/dr-asha-s-vijay',
  '/dr-asha-s-vijay-opens-lifes-journey-avala-hejje': '/fertility-experts/dr-asha-s-vijay',
  '/dr-priyanka-rani': '/fertility-experts/dr-priyanka-rani',
  '/dr-srinivas-b-v': '/fertility-experts',
  '/dt_doctors/asha-s-vijay': '/fertility-experts/dr-asha-s-vijay',
  '/embed': '/',
  '/endometrial-rejuvenation': '/blogs/endometrial-rejuvenation',
  '/endometriosis': '/blogs/endometriosis-an-introduction',
  '/endometriosis-surgical-management': '/blogs/endometriosis-an-introduction',
  '/features/Best in Class Facilities': '/features/best-in-class-facilities',
  '/features/paripoorna-2023': '/features/paripoorna',
  '/fertility': '/fertility-center',
  '/fertility-': '/fertility-center',
  '/fertility-experts/dr-deepthi-venkatesh': '/fertility-experts',
  '/fertility-tests-for-women': '/blogs/fertility-tests-for-women',
  '/garbhagudi-': '/',
  '/garbhagudi-ivf-center-association-bmc-vanivilas-hospital-bengaluru-conducted-cme-infertility-17th-august-2017':
    '/',
  '/garbhagudi-ivf-centre-article-in-profit-plus-kannada-magazine-3': '/',
  '/garbhagudi-ivf-centre-article-profit-plus-kannada-magazine': '/',
  '/garbhagudi-ranked-among-the-top-10-ivf-centres-in-india-by-times-of-india':
    '/about/awards-and-accolades/garbhagudi-ranked-among-top-10-ivf-centres-in-india-times-health-survey',
  '/genital-tuberculosis-infertilty': '/blogs/genital-tuberculosis-and-infertilty',
  '/how-to-conceive-if-you-have-pcos': '/blogs/getting-pregnant-with-pcos',
  '/how-to-improve-': '/',
  '/improve-fertility-pcos-women': '/blogs/how-to-improve-fertility-in-pcos-women',
  '/infertility/diagnosis-and-treatment':
    '/blogs/female-infertility-explained-diagnosis-and-treatments',
  '/infertility/symptoms-': '/blogs/an-overview-of-infertility-symptoms-and-causes',
  '/infertility/symptoms-and-causes': '/blogs/an-overview-of-infertility-symptoms-and-causes',
  '/in-vitro-fertilization': '/treatments/ivf-treatment-in-bangalore',
  '/ivf-success-rates': '/features/success-rates-of-ivf',
  '/know-when-icsi-or-ivf-is-preferred-in-infertility-treatment':
    '/blogs/is-icsi-or-ivf-preferred-in-infertility-treatment',
  '/lifestyle-modifications-male-infertility-treatment':
    '/blogs/why-lifestyle-changes-are-crucial-for-couples-undergoing-fertility-treatments',
  '/male-infertility-azoospermia-case-study-by-dr-chaithra-s-k':
    '/blogs/what-is-azoospermia-what-are-the-treatment-options',
  '/male-infertility-work': '/blogs/male-infertility-work-up',
  '/obesity-and-infertility': '/blogs/the-impact-of-obesity-on-fertility',
  '/or': '/',
  '/ovulation-disorders-and-infertility': '/blogs/ovulation-disorders-and-infertility',
  '/paripoorna': '/features/paripoorna',
  '/pcos-and-infertility': '/blogs/pcos-and-infertility',
  '/pcos-healthy-diet-tips': '/blogs/decoding-pcos-revealing-foods-to-avoid-for-better-health',
  '/pregnancy-male-infertility': '/blogs/pregnancy-and-male-infertility',
  '/six-major-causes-of-male-infertility': '/blogs/six-major-causes-of-male-infertility',
  '/solutions/cost-of-egg-donation-in-bangalore': '/solutions/egg-freezing-in-bangalore',
  '/strict-covid-19-': '/blogs/covid-19-and-its-impact-on-infertility-treatment',
  '/strict-covid-19-guidelines-followed-across-all-our-centres':
    '/blogs/covid-19-and-its-impact-on-infertility-treatment',
  '/suffering-from-infertility-pelvic-adhesions-could-be-the-culprit':
    '/blogs/are-you-suffering-from-infertility-pelvic-adhesions-could-be-the-culprit',
  '/surgical-management-endometriosis':
    '/blogs/laparoscopy-for-endometriosis-how-it-can-improve-fertility',
  '/tag/best-infertility-clinic-in-bangalore/page/1':
    '/fertility-center/best-infertility-clinic-bangalore',
  '/tag/diabetes-and-infertility': '/blogs/infertility-and-diabetes',
  '/tag/diet-plan': '/blogs/nutrition-for-ivf',
  '/tag/endometriosis': '/blogs/endometriosis',
  '/tag/ivf-treatment': '/treatments',
  '/tag/ivf-treatment/g': '/',
  '/tag/ivf-treatment/page/1': '/treatments/ivf-treatment-in-bangalore',
  '/tag/non-obstructive-azoospermia': '/solutions/azoospermia-treatment-in-bangalore',
  '/tag/pregnancy': '/blogs/pregnancies-and-miscarriages',
  '/talk-series-by-dr-asha-s-vijay-egg-freezing': '/fertility-experts/dr-asha-s-vijay',
  '/the-journey-of-divinity-from-an-idea-to-reality':
    '/blogs/the-journey-of-divinity-from-an-idea-to-reality',
  '/tubal-disease-and-infertility': '/blogs/tubal-disease-and-infertility',
  '/understanding-ivf-treatment-and-its-success-rate': '/blogs/ivf-and-success-rates',
  '/what-is-endometriosis-and-why-it-causes-infertility':
    '/blogs/what-is-endometriosis-and-why-it-causes-infertility',
  '/what-is-infertility': '/blogs/what-is-infertility',
  '/what-is-iui-intrauterine-': '/blogs/what-is-iui-intrauterine-insemination',
  '/what-is-iui-intrauterine-insemination': '/blogs/what-is-iui-intrauterine-insemination',
  '/womens-fertility': '/blogs/fertility-tests-for-women',
  '/womens-fertility-health': '/blogs/fertility-tests-for-women',
  '/blogs/what-is-the-cost-of-ivf-treatment-in-india':
    '/treatments/ivf-treatment-cost-in-bangalore',
  '/cost-of-ivf-in-india': '/treatments/ivf-treatment-cost-in-bangalore',
  '/en_US/eshre-2018': '/blogs/pcos-symptoms-and-treatment',
  '/executive-team': '/about/overview',
  '/free-infertility-screening-evaluation-camps': '/',
  '/ivf-egg-donation': '/treatments/egg-freezing',
  '/fertility-consultants/cost-of-embryo-donation-in-bangalore': '/treatments/egg-freezing',
  '/packages': '/treatments/ivf-treatment-cost-in-bangalore',
  '/solutions/cost-of-embryo-donation-in-bangalore': '/treatments/egg-freezing',
  '/*****-bank-and-legal-aspects-all-you-need-to-know': '/treatments/*****-freezing',
  '/tv9': '/',
  '/video-when-to-consult-fertility-specialist': '/blogs/when-to-see-a-fertility-specialist',
  '/facilities/cost-of-egg-donation-in-bangalore': '/treatments/egg-freezing',
  '/blogs/understanding-ivf-treatment-and-its-success-rate': '/blogs/ivf-and-success-rates',
  '/blogs/understanding-menopause-a-natural-biological-process':
    '/blogs/can-a-women-get-pregnant-after-menopause',
  '/careers/academic-coordinator': '/careers',
  '/category/doctors': '/fertility-experts',
  '/category/dr-sophia': '/fertility-experts',
  '/category/news': '/publications',
  '/partnership': '/contact/partnership',
  '/pre-implantation-genetic-diagnosis':
    '/resources/diagnosis/pre-implantation-genetic-diagnosis-pgd',
  '/services_iui': '/treatments/iui-treatment-in-bangalore',
  '/success-rate-demo': '/contact/success-rates-of-ivf',
  '/success-rates-of-ivf': '/contact/success-rates-of-ivf',
  '/tese-infertility-treatment': '/treatments/pesa-and-tesa',
  '/treatments-for-male-infertility-best-ivf-centre-in-bangalore': '/treatments/pesa-and-tesa',
  '/ultrasound-scan-in-bangalore': '/resources/diagnosis/ultrasound-scan',
  '/youve-been-diagnosed-': '/resources/diagnosis/ultrasound-scan',
  '/3746-2': '/blogs/page/1',
  '/about/executive-': '/about/overview',
  '/azoospermia-treatment-options': '/fertility-center/azoospermia-treatment-in-bangalore',
  '/blocked-fallopian-tubes-and-infertility': '/resources/causes/blocked-fallopian-tubes',
  '/blogs/best-': '/blogs/how-to-select-the-best-ivf-center',
  '/blogs/dos-and-donts-': '/blogs/dos-and-donts-after-embryo-transfer',
  '/blogs/infertility-awareness-why-education-matters':
    '/blogs/breaking-the-taboo-around-infertility-stories-of-strength',
  '/blogs/life-with-pcod-after-marriage-prioritising-health-and-nurturing-relationships':
    '/blogs/pcod-problem-after-marriage',
  '/another-extraordinary-achievement-by-team-garbhagudi': '/about/awards-and-accolades',
  '/treatments/egg-donation': '/treatments',
  '/about-overview/': '/about/overview',
  '/best-fertility-hospital-in-bangalore/': '/treatments/ivf-treatment-in-bangalore',
  '/best-ivf-center-in-bangalore/': '/treatments/ivf-treatment-in-bangalore',
  '/blog/': '/blogs/page/1',
  '/blogs/do-sexually-transmitted-diseases-affect-fertilit':
    '/blogs/can-sexually-transmit-diseases-affect-infert',
  '/blogs/the-psychology-of-egg-donation-insights-from': '/treatments/ivf-treatment-egg-freezing',
  '/contact.html': '/gg-care',
  '/en_US/-': '/',
  '/en_US/male-infertility-work': '/blogs/male-infertility-work-up',
  '/en_US/profile/asha-s-vijay/': '/fertility-experts/dr-asha-s-vijay',
  '/fallopian-tube-blockage-symptoms': '/blogs/blocked-fallopian-tubes-diagnosis-and-trea',
  '/fertility-tests-for-men/': '/blogs/fertility-tests-for-men-2',
  '/fertility-tests-for-men-2/': '/blogs/fertility-tests-for-men-2',
  '/home/': '/',
  '/infertility-clinic-electronic-city-bangalore/': '/locations/electronic-city',
  '/partnership/': '/contact/partnership',
  '/sperms-male-infertility/': '/blogs/sperms-and-male-infertility',
  '/treatments-for-male-infertility-best-ivf-centre-in-ban': '/treatments/pesa-and-tesa',
  '/what-is-ivf/': '/blogs/what-is-ivf',
  '/akhila-karnataka-satsangha-bhajana-maha-ma': '/fertility-experts/dr-asha-s-vijay',
  '/blogs/infertility-awareness-why-education-ma':
    '/blogs/breaking-the-taboo-around-infertility-storie',
  '/blogs/life-with-pcod-after-marriage-prioritisin': '/blogs/pcod-problem-after-marriage',
  '/id/forgotpassword': '/blogs/page/1',
  '/account/login': '/blogs/page/1',
  '/account/forgotpassword': '/',
  '/contact5.html': '/gg-care',
  '/blogs/the-amazing-race-how-tiny-swimmers-b': '/blogs/what-is-spermatogenesis',
  '/blogs/understanding-ivf-treatment-and-its-suc': '/blogs/ivf-and-success-rates',
  '/blogs/understanding-menopause-a-natural-bi': '/blogs/can-a-women-get-pregnant-after-menopau',
  '/blogs/what-made': '/blogs/what-made-you-get-out-of-shape',
  '/careers/associate-lead-direct-sales': '/careers',
  '/careers/electrician': '/careers',
  '/common-infections-pelvis-leading-onto-inferti':
    '/blogs/common-infections-of-pelvis-leading-onto-',
  '/contact2.html': '/gg-care',
  '/contact7.html': '/gg-care',
  '/diet-in-infertility/': '/blogs/diet-in-infertility',
  '/dr-asha-s-vijay-next-iui-garbhagudi-ivf-centre-t': '/fertility-experts/dr-asha-s-vijay',
  '/dr-asha-s-vijay-program': '/fertility-experts/dr-asha-s-vijay',
  '/effect-endometriosis-fertility': '/blogs/effect-of-endometriosis-on-fertility',
  '/fertility-center/cost-of-egg-donation-in-bangal': '/solutions/egg-freezing-in-bangalore',
  '/fertility-center/ivf-treatment-cost-in-bangalore':
    '/treatments/ivf-treatment-cost-in-bangalore',
  '/fertility-consultants/cost-of-egg-donation-in-b': '/solutions/egg-freezing-in-bangalore',
  '/fertility-consultants/cost-of-embryo-donation-': '/treatments/egg-freezing',
  '/fertility-tests-for-women/': '/blogs/fertility-tests-for-women',
  '/garbhagudi-ivf-center-association-bmc-vanivila': '/',
  '/garbhagudi-ivf-centre-article-in-profit-plus-kan': '/',
  '/lifestyle-modifications-male-infertility-treatme':
    '/blogs/why-lifestyle-changes-are-crucial-for-coupl',
  '/male-infertility-azoospermia-case-study-by-dr-':
    '/blogs/what-is-azoospermia-what-are-the-treatme',
  '/our-happy-couples': '/',
  '/pcos-and-infertility/': '/blogs/pcos-and-infertility',
  '/pregnancy-male-infertility/': '/blogs/pregnancy-and-male-infertility',
  '/solutions/cost-of-embryo-donation-in-bangalo': '/treatments/egg-freezing',
  '/*****-bank-and-legal-aspects-all-you-need-to': '/treatments/*****-freezing',
  '/tag/rajyotsava': '/',
  '/talk-series-by-dr-asha-s-vijay-egg-freezing/': '/fertility-experts/dr-asha-s-vijay',
  '/understanding-ivf-treatment-and-its-success-r': '/blogs/ivf-and-success-rates',
  '/video-when-to-consult-fertility-specialist/': '/blogs/when-to-see-a-fertility-specialist',
  '/what-is-infertility/': '/blogs/what-is-infertility',
  '/what-is-iui-intrauterine-insemination/': '/blogs/what-is-iui-intrauterine-insemination',
  '/womens-day-celebrations-govt-karnataka/': '/',
  '/youve-been-diagnosed-with-unexplained-infertility-what-next/': '/blogs/unexplained-infertility',
  '/womens-day-wishes-garbhagudi/': '/',
  '/what-is-iui-': '/blogs/what-is-iui-intrauterine-insemination',
  '/video-male-infertility': 'https://www.garbhagudi-ivf.com/male-infertility',
  '/treatments/ivf-treatment-in-bangalore/egg-freezing-quiz-form':
    '/treatments/ivf-treatment-egg-freezing',
  '/treatments/ivf-treatment-in-bangalore/egg-freezing-quiz':
    '/treatments/ivf-treatment-egg-freezing',
  '/topic-pelvic-infections-infertility-sub-topic-complications-treatment/':
    '/blogs/common-infections-of-pelvis-leading-onto-infertility',
  '/tag/male-infertility/': 'https://www.garbhagudi-ivf.com/male-infertility',
  '/tag/infertility': '/treatments/infertility-treatment-in-bangalore',
  '/tag/how-to-get-pregnant': '/treatments/natural-pregnancy',
  '/tag/fertility-test': '/blogs/fertility-tests-for-women',
  '/tag/best-infertility-clinic-in-bangalore/page/2':
    '/fertility-center/best-infertility-clinic-bangalore',
  '/solutions/ivf-treatment-cost-in-bangalore': '/treatments/ivf-treatment-cost-in-bangalore',
  '/solutions/cost-of-iui-in-bang': '/solutions/cost-of-iui-in-bangalore',
  '/side-navigation/nutrition-weight': '/blogs/fertility-and-nutrition',
  '/role-of-ultra-sound-in-infertility':
    '/blogs/the-role-of-advanced-ultrasound-techniques-in-detecting-fertility-issues',
  '/resources/facts': '/',
  '/prolactin-hormonal-disorders-and-infertility': '/blogs/prolactin-levels-in-women',
  '/prepare-yourself-mentally-physically-and-financially-for-a-fertility-treatment':
    'https://www.garbhagudi-ivf.com',
  '/poor-ovarian-reserve-por': '/blogs/poor-ovarian-reserve-por',
  '/obesity-effects-fertility': '/blogs/the-impact-of-obesity-on-fertility',
  '/ivf-precautions-post-embryo-transfer': '/blogs/ivf-precautions-post-embryo-transfer',
  '/introduction-incidence-prevalence-male-infertility':
    '/blogs/introduction-incidence-and-prevalence-of-male-infertility',
  '/infertility-men-women-common-causes': '/blogs/causes-of-male-and-female-infertility',
  '/infertility/departments-and-specialties': '/blogs/what-is-infertility',
  '/infertility/departments': '/blogs/what-is-infertility',
  '/how-to-choose-a-fertility-center': '/blogs/how-to-choose-a-fertility-center',
  '/how-does-ivf-at-home-work': '/blogs/how-does-ivf-from-home-work',
  '/garbhagudi-ivf-centre-article-in-profit-plus-kannada-magazine': '/',
  '/fertility-consultants/ivf-treatment-cost-in-bangalore':
    '/treatments/ivf-treatment-cost-in-bangalore',
  '/faq': '/resources/faq',
  '/facilities/ivf-treatment-cost-in-bangalore': '/treatments/ivf-treatment-cost-in-bangalore',
  '/executive-team/:slug': '/fertility-experts',
  '/even-*****-and-eggs-come-with-an-expiration-date':
    '/blogs/even-*****-and-eggs-come-with-an-expiration-date',
  '/even-*****-and-eggs-': '/blogs/even-*****-and-eggs-come-with-an-expiration-date',
  '/dr-chinmayie-r': '/fertility-experts',
  '/dr-chaitra-s-k': '/fertility-experts',
  '/dr-asha-s-vijay-receives-the-rotary-rajyotsava-award-2019': '/about/awards-and-accolades',
  '/does-hyperthyroidism-cause-infertility-in-women': '/fertility-experts/dr-asha-s-vijay',
  '/diagnosis/ultrasound-scan': '/resources/diagnosis/ultrasound-scan',
  '/diagnosis/*****-analysis': '/resources/diagnosis/*****-analysis',
  '/diagnosis/pre-implantation-genetic-screening-pgs':
    '/resources/diagnosis/pre-implantation-genetic-screening-pgs',
  '/diagnosis/pre-implantation-genetic-diagnosis-pgd':
    '/resources/diagnosis/pre-implantation-genetic-diagnosis-pgd',
  '/diagnosis/ovarian-reserve-tests-ort': '/resources/diagnosis/ovarian-reserve-tests-ort',
  '/diagnosis/hysterosalpingogram': '/resources/diagnosis/hysterosalpingogram',
  '/diagnosis/endometrial-receptivity-array-era':
    '/resources/diagnosis/endometrial-receptivity-array-era',
  '/diagnosis/blood-investigations': '/resources/diagnosis/blood-investigations',
  '/causes-and-risk-factors-of-poor-ovarian-reserve':
    '/blogs/causes-and-risk-factors-of-poor-ovarian-reserve',
  '/causes/surgical-complications': '/resources/causes/surgical-complications',
  '/causes/polycystic-ovarian-syndrome-pcos': '/resources/causes/polycystic-ovarian-syndrome-pcos',
  '/causes/pelvic-inflamatory-disease': '/resources/causes/pelvic-inflamatory-disease',
  '/blogs/safe-parenthood-with-donor-insemination': '/',
  '/causes/ovulation-disorders': '/resources/causes/ovulation-disorders',
  '/causes/obesity-and-fertility': '/blogs/the-impact-of-obesity-on-fertility',
  '/causes/hormonal-disorders': '/resources/causes/hormonal-disorders',
  '/causes/blocked-fallopian-tubes':
    '/blogs/blocked-fallopian-tubes-diagnosis-and-treatment-options',
  '/category/garbhagudi_ivf': '/',
  '/blogs/understanding-how-endocannabinoid-receptors-influence-reproduction':
    '/blogs/understanding-how-endocannabinoid-receptors-influence-reproduction1',
  '/blogs/*****-bank-and-legal-aspects-all-you-need-to-know':
    '/blogs/the-future-of-*****-and-egg-banking-in-ivf-treatments',
  '/what-is-ivf': '/blogs/what-is-ivf',
  '/sperms-male-infertility': '/blogs/sperms-and-male-infertility',
  '/signs-of-infertility-in-young-women': '/blogs/signs-of-infertility-in-young-women',
  '/pgs-testing': '/blogs/what-are-pgd-and-pgs',
  '/ivf-clinic-in-hanumanth-nagar-bangalore': '/locations/hanumanthanagar',
  '/iui-treatment-cost-in-india-2': '/treatments/iui-treatment-in-bangalore',
  '/is-infertility-a-womans-problem':
    '/blogs/intracytoplasmic-*****-injection-icsi-when-is-it-recommended',
  '/intracytoplasmic-*****-injection':
    '/blogs/intracytoplasmic-*****-injection-icsi-when-is-it-recommended',
  '/how-to-select-the-best-ivf-center': '/blogs/how-to-select-the-best-ivf-center',
  '/fertility-centre-in-jayanagar-bangalore': '/locations/jayanagar',
  '/en_US/profile/asha-s-vijay': '/fertility-experts/dr-asha-s-vijay',
  '/blogs/what-is-ivf-how-does-it-work': '/blogs/what-is-ivf',
  '/blogs/icsi-treatment-in-bangalore': '/treatments/icsi-treatment-in-bangalore',
  '/blogs/do-sexually-transmitted-diseases-affect-fertility':
    '/blogs/can-sexually-transmit-diseases-affect-infertility',
  '/best-fertility-hospital-in-kalyan-nagar-bangalore': '/locations/kalyan-nagar',
  '/blogs/know-about-gestational-surrogacy': '/',
  '/blogs/infertility-in-india-': '/blogs/infertility-in-india-statistics-and-challenges',
  '/blogs/fertility-and': '/fertility-center',
  '/biological-clock-ticking-ladies-beware-aware':
    '/blogs/your-biological-clock-is-ticking-ladies-be-aware',
  '/awards-and-accolades/national-excellency-award-2024-awarded-by-the-world-health-congress':
    '/about/awards-and-accolades',
  '/awards-and-accolades/icon-of-the-year-ivf-south-dr-asha-s-vijay':
    '/about/awards-and-accolades/icon-of-the-year-ivf-south-dr-asha-s-vijay',
  '/awards-and-accolades/garbhagudi-recognised-as-best-ivf-and-fertility-hospital-in-india':
    '/about/awards-and-accolades/garbhagudi-recognised-as-best-ivf-and-fertility-hospital-in-india',
  '/awards-and-accolades/garbhagudi-certified-healthy-workplace':
    '/about/awards-and-accolades/garbhagudi-certified-healthy-workplace',
  '/awards-and-accolades/fastest-growing-ivf-centre-in-bangalore':
    '/about/awards-and-accolades/fastest-growing-ivf-centre-in-bangalore',
  '/awards-and-accolades/best-ivf-clinic-of-the-year-ethealth':
    '/about/awards-and-accolades/best-ivf-clinic-of-the-year-ethealth',
  '/executive-team/pushpalatha-ms': '/fertility-experts',
  '/executive-team/dr-asha-s-vijay': '/fertility-experts',
  '/executive-team/hari-srinivasan': '/fertility-experts',
  '/awards-and-accolades/garbhagudi-ranked-among-top-10-ivf-centres-in-india-times-health-survey':
    '/about/awards-and-accolades',
  '/executive-team/vijay-kumar-sheshadri': '/fertility-experts',
  '/fertility-experts/dr-ranjitha-k-a': '/fertility-experts',
  '/blogs/understanding-the-cost-of-laparoscopy-in-bangalore':
    '/solutions/cost-of-laparoscopy-in-bangalore',
  '/fertility-center/cost-of-iui-in-bangalore': '/solutions/cost-of-iui-in-bangalore',
  '/facilities/best-fertility-treatment-in-bangalore':
    '/solutions/best-fertility-treatment-in-bangalore',
  '/fertility-consultants/best-fertility-doctors-in-bangalore':
    '/solutions/best-fertility-doctors-in-bangalore',
  '/fertility-consultants/best-fertility-treatment-in-bangalore':
    '/solutions/best-fertility-treatment-in-bangalore',
  '/fertility-consultants/male-infertility-treatment-in-bangalore':
    '/solutions/male-infertility-treatment-in-bangalore',
  '/fertility-consultants/best-fertility-center-in-bangalore':
    '/fertility-center/best-fertility-center-in-bangalore',
};

export function middleware(req: NextRequest) {
  const url = req.nextUrl.clone();

  let pathname =
    url.pathname.endsWith('/') && url.pathname !== '/' ? url.pathname.slice(0, -1) : url.pathname;

  if (redirects[pathname]) {
    url.pathname = redirects[pathname];
    return NextResponse.redirect(url, 301);
  }

  return NextResponse.next();
}

export const config = {
  matcher: Object.keys(redirects),
};
